//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDD_THEMEDLG                    101
#define IDD_SCRSVRDLG                   103
#define IDD_BACKGROUNDDLG               105
#define IDD_APPEARANCEDLG               107
#define IDD_SETTINGSDLG                 109
#define IDD_APPEARANCEBOX               111
#define IDD_EFFECTSDLG	                113
#define IDD_THEMECHNGDLG	            115
#define IDD_ADVANCEDDLG                127
#define IDD_ADAPTERDLG                 128
#define IDD_MONITORDLG                 129
#define IDD_GENERALDLG                 130
#define IDD_TROUBLESHOOTDLG            131
#define IDI_ADAPTER                    132
#define IDI_MONITOR                    133
#define IDD_CUSTOMDPIDLG                134
#define IDD_THEMEUI_COLOR_PICKER         140
#define IDD_DESKTOPICONSDLG              142
#define IDC_CUSTOMDPIPERCENT            2061
#define IDC_CUSTOMDPIRULER              2062
#define IDC_CUSTOMDPISAMPLE             2063
#define IDC_CUSTOMDPIDESC               2064
#define IDC_CUSTOMDPISCALELABEL         2065
#define IDI_ICON1                       117
#define IDS_THEMESCPL                   118
#define IDS_THEMESDESC                  119
#define IDS_ACCEL_NONE                  2673
#define IDS_ACCEL_REDUCED               2674
#define IDS_ACCEL_FULL                  2675
#define IDS_MY_CURRENT_THEME             2009
#define IDS_MODIFIED_THEME_FORMAT        2025
#define IDS_BROWSE_THEMES                2010
#define IDS_MORE_THEMES_ONLINE           2015
#define IDS_WINDOWS_XP                   2017
#define IDS_NORMAL_SIZE                  2002
#define IDS_LARGE_SIZE                   2020
#define IDS_EXTRA_LARGE_SIZE             2021
#define IDS_WINDOWS_CLASSIC_STYLE        2003
#define IDS_STANDARD_SMOOTHING           2625
#define IDS_CLEARTYPE_SMOOTHING          2624
#define IDS_FADE_EFFECT                 2622
#define IDS_SCROLL_EFFECT               2623
#define IDS_EFFECTS_TITLE               2621
#define IDS_NORMAL_DPI                   2045
#define IDS_LARGE_DPI                    2046
#define IDS_CUSTOM_DPI                   2666
#define IDS_NOT_ACTIVE_LABEL            2652
#define IDS_PRIMARY_DISPLAY_LABEL       2653
#define IDS_LOWEST_COLOR_QUALITY        2655
#define IDS_LOW_COLOR_QUALITY           2656
#define IDS_MEDIUM_COLOR_QUALITY        2658
#define IDS_HIGH_COLOR_QUALITY          2659
#define IDS_HIGHEST_COLOR_QUALITY       2660
#define IDS_DISPLAY_PROPERTIES          5000
#define IDS_THEME_FILE_INVALID          5001
#define IDS_THEME_FILE_UNAVAILABLE      5002
#define IDS_ERROR_LOADING_THEME         5003
#define IDS_WINDOWS_XP_STYLE            5004
#define IDS_ZUNE                        5005
#define IDS_ROYALE                      5006
#define IDS_ROYALE_NOIR                 5007
#define IDS_CUSTOM_CLASSIC              5008
#define IDS_THEME_FILE_LABEL            5009
#define IDS_SAVE_THEME_AS               5010
#define IDS_BROWSE                       5011
#define IDS_DESKTOP_ITEMS_OPEN_ERROR    5012
#define IDS_NOT_AVAILABLE               5013
#define IDS_DEFAULT_REFRESH_RATE        5014
#define IDS_SETTINGS_GENERAL            5015
#define IDS_SETTINGS_ADAPTER            5016
#define IDS_SETTINGS_MONITOR            5017
#define IDS_SETTINGS_TROUBLESHOOT       5018
#define IDS_DESKTOP_ICON_COMPUTER       5019
#define IDS_DESKTOP_ICON_DOCUMENTS      5020
#define IDS_DESKTOP_ICON_NETWORK        5021
#define IDS_DESKTOP_ICON_RECYCLE_FULL   5022
#define IDS_DESKTOP_ICON_RECYCLE_EMPTY  5023
#define IDS_DESKTOP_ICON_INTERNET       5024
#define IDS_DESKTOP_ICON_CONTROL_PANEL  5025
#define IDS_THEME_SNAPSHOT_MISSING      5026
#define IDS_BROWSE_FOR_THEME            5027
#define IDS_THEME_ADD_TO_LIST_ERROR     5028
#define IDS_CURRENT_THEME_FILE_MISSING  5029
#define IDS_DEFAULT_THEME_FILENAME     5030
#define IDS_DEFAULT_THEME_FILENAME_ERROR 5031
#define IDS_THEME_COPY_ERROR            5032
#define IDS_THEME_NAME_WRITE_ERROR      5033
#define IDS_THEME_CLASSIC_SAVE_ERROR    5034
#define IDS_THEME_STAGED_COPY_ERROR     5035
#define IDS_THEME_ADD_ERROR             5036
#define IDS_THEME_CLASSIC_APPLY_ERROR   5037
#define IDS_THEME_DELETE_ERROR          5038
#define IDS_THEME_PREPARE_ERROR         5039
#define IDS_THEME_APPLY_ERROR           5040
#define IDS_THEME_APPLIED_CLASSIC_ERROR 5041
#define IDS_CLASSIC_SCHEME_APPLY_ERROR  5042
#define IDS_STANDARD_SCHEME_APPLY_ERROR 5043
#define IDS_ALL_FILES_LABEL             5044
#define IDS_COLOR_SCHEME_SAVE_ERROR     5045
#define IDS_COLOR_SCHEME_RETAIN_ERROR   5046
#define IDS_VISUAL_STYLE_APPLY_ERROR    5047
#define IDS_CLASSIC_DERIVATIVE_SYNC_ERROR 5048
#define IDS_CLASSIC_DERIVATIVE_MISSING  5049
#define IDS_CLASSIC_DERIVATIVE_SAVE_ERROR 5050
#define IDS_VISUAL_DERIVATIVE_SYNC_ERROR 5051
#define IDS_ICON_SIZE_SAVE_ERROR        5052
#define IDS_ICON_SIZE_UPDATE_ERROR      5053
#define IDS_WALLPAPER_DERIVATIVE_SYNC_ERROR 5054
#define IDS_DPI_READ_ERROR              5055
#define IDS_DPI_RESTART_NOTICE          5056
#define IDS_CHANGE_DPI_TITLE            5057
#define IDS_DPI_SAVE_ERROR              5058
#define IDS_GRAPHICS_PROFILE_UNSUPPORTED 5059
#define IDS_GRAPHICS_TITLE              5060
#define IDS_GPU_SCHEDULING_RESTART      5061
#define IDS_VRR_ENABLED                 5062
#define IDS_VRR_DISABLED                5063
#define IDS_GRAPHICS_PROFILE_SAVE_ERROR 5064
#define IDS_VRR_ENABLE_ERROR            5065
#define IDS_VRR_DISABLE_ERROR           5066
#define IDS_ADAPTER_PROPERTIES_ERROR    5067
#define IDS_ALL_MODES_OPEN_ERROR        5068
#define IDS_MONITOR_PROPERTIES_ERROR    5069
#define IDS_MONITOR_CONFIG_READ_ERROR   5070
#define IDS_MODE_FILTER_SAVE_ERROR      5071
#define IDS_REFRESH_RATE_APPLY_ERROR    5072
#define IDS_MONITOR_CONFIGURATION_CHANGED 5073
#define IDS_EXTEND_MONITOR_FIRST        5074
#define IDS_MONITOR_DEVICE_MISSING      5075
#define IDS_MONITORS_SHARE_DEVICE       5076
#define IDS_SAVED_MONITOR_CONFIG_READ_ERROR 5077
#define IDS_CURRENT_DISPLAY_CONFIG_READ_ERROR 5078
#define IDS_MONITOR_ARRANGEMENT_REJECTED 5079
#define IDS_MONITOR_ARRANGEMENT_SAVE_ERROR 5080
#define IDS_MONITOR_ARRANGEMENT_APPLY_ERROR 5081
#define IDS_MONITOR_ENABLE_PROMPT       5082
#define IDS_DPI_SAMPLE_FONT             2670
#define IDS_DPI_SAMPLE_FORMAT           2671
#define IDS_MONITOR_NUMBER_FORMAT       2643
#define IDS_SECONDARY_DISPLAY_LABEL     2654
#define IDS_ADVANCED_DISPLAY_TITLE_FORMAT 5087
#define IDS_DISPLAY_MODE_FORMAT         5088
#define IDS_HERTZ_FORMAT                5089
#define IDS_DISPLAY_MEMORY_PLACEHOLDER  5090
#define IDS_DISPLAY_LIST_FORMAT         5091
#define IDS_RESOLUTION_FORMAT           5092
#define IDS_COLOR_DEPTH_4              5093
#define IDS_COLOR_DEPTH_8              5094
#define IDS_COLOR_DEPTH_16             5095
#define IDS_COLOR_DEPTH_24             5096
#define IDS_COLOR_DEPTH_32             5097
#define IDS_COLOR_DEPTH_GENERIC_FORMAT 5098
#define IDS_MODE_LINE_FORMAT            5099
#define IDS_MODE_LINE_DEFAULT_FORMAT    5100
#define IDS_NO_VALID_MODES              5101
#define IDS_ALL_PICTURE_FILES_LABEL     5102
#define IDS_REVERT_COUNTDOWN            2640
#define IDS_STYLE_FORMAT                5103
#define IDS_LUNA_STYLE                  5111
#define IDS_OLIVE_STYLE                 5112
#define IDS_SILVER_STYLE                5113
#define IDS_XP_STYLE_FOLDER             5114
#define IDS_ROYALE_STYLE_FOLDER         5115
#define IDS_ROYALE_STYLE                5116
#define IDS_THEME_COPY_BLOCKED          5117
#define IDS_GRAPHICS_SETTINGS_READ_ERROR 5108
#define IDS_DESKTOP_ITEMS_OPEN_ERROR_CODE 5109
#define IDS_WINDOWS_CLASSIC_NAME        2016
#define IDS_DEFAULT_MONITOR             2627
#define IDS_DPI_DESCRIPTION_FORMAT      2668
#define IDS_ADAPTER_MEMORY_FORMAT       5110
#define IDB_4BIT						120
#define IDB_8BIT						121
#define IDB_BITMAP2						122
#define IDB_16BIT						123
#define IDB_24BIT						124
#define IDB_32BIT						125
#define IDB_BITMAP1                     126

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
